// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class Achieve
{
        public const string achievement_cancer = "CgkI2tzJ6JcSEAIQEQ"; // <GPGSID>
        public const string achievement_passing_all_levels = "CgkI2tzJ6JcSEAIQDQ"; // <GPGSID>
        public const string achievement_4_continuous_jumps = "CgkI2tzJ6JcSEAIQAw"; // <GPGSID>
        public const string leaderboard_the_abnormal_whirlpool = "CgkI2tzJ6JcSEAIQCA"; // <GPGSID>
        public const string achievement_libra = "CgkI2tzJ6JcSEAIQEw"; // <GPGSID>
        public const string leaderboard_continuous_jumps_through_all_levels = "CgkI2tzJ6JcSEAIQCQ"; // <GPGSID>
        public const string achievement_unlock_the_abnormal_whirlpool = "CgkI2tzJ6JcSEAIQBQ"; // <GPGSID>
        public const string leaderboard_the_chaotic_milky_way = "CgkI2tzJ6JcSEAIQBw"; // <GPGSID>
        public const string achievement_sagittarius = "CgkI2tzJ6JcSEAIQEA"; // <GPGSID>
        public const string achievement_aries = "CgkI2tzJ6JcSEAIQEg"; // <GPGSID>
        public const string achievement_passing_the_tutorial = "CgkI2tzJ6JcSEAIQAg"; // <GPGSID>
        public const string achievement_aquarius = "CgkI2tzJ6JcSEAIQDg"; // <GPGSID>
        public const string achievement_pisces = "CgkI2tzJ6JcSEAIQDw"; // <GPGSID>
        public const string achievement_unlock_the_chaotic_milky_way = "CgkI2tzJ6JcSEAIQBA"; // <GPGSID>

}

